// Code generated by MVRP Codegen Util. DO NOT EDIT.

package sale

import (
	"context"
	"database/sql"
	"mvrp/data/model/sale"
	"mvrp/domain/dto"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
)

func (r *SaleRepository) ListAllOrderConfirmationItems(ctx context.Context, exec boil.ContextExecutor) (sale.OrderConfirmationItemSlice, error) {
	return sale.OrderConfirmationItems().All(ctx, exec)
}
func (r *SaleRepository) SearchOrderConfirmationItems(ctx context.Context, exec boil.ContextExecutor, dto dto.SearchOrderConfirmationItemDTO) (sale.OrderConfirmationItemSlice, error) {
	return sale.OrderConfirmationItems(
		qm.Limit(dto.ItemsPerPage),
		qm.Offset((dto.ItemsPerPage*dto.Page)-dto.ItemsPerPage),
		qm.GroupBy("id"),
		qm.OrderBy(dto.OrderBy+" "+"ASC"),
	).All(ctx, exec)
}

func (r *SaleRepository) GetOrderConfirmationItemByID(ctx context.Context, exec boil.ContextExecutor, id int) (*sale.OrderConfirmationItem, error) {
	return sale.FindOrderConfirmationItem(ctx, exec, id)
}

func (r *SaleRepository) CreateOrderConfirmationItem(ctx context.Context, exec boil.ContextExecutor, m *sale.OrderConfirmationItem) error {
	id, err := r.GetNextEntryOrderConfirmationItemID(ctx, exec)
	if err != nil {
		return err
	}
	m.ID = id
	return m.Insert(ctx, exec, boil.Infer())
}

func (r *SaleRepository) UpdateOrderConfirmationItem(ctx context.Context, exec boil.ContextExecutor, m *sale.OrderConfirmationItem) error {
	_, err := m.Update(ctx, exec, boil.Infer())
	return err
}

func (r *SaleRepository) UpsertOrderConfirmationItem(ctx context.Context, exec boil.ContextExecutor, m *sale.OrderConfirmationItem) error {
	return m.Upsert(ctx, exec, true, nil, boil.Infer(), boil.Infer())
}

func (r *SaleRepository) DeleteOrderConfirmationItem(ctx context.Context, exec boil.ContextExecutor, m *sale.OrderConfirmationItem) error {
	_, err := m.Delete(ctx, exec)
	return err
}

func (r *SaleRepository) OrderConfirmationItemExists(ctx context.Context, exec boil.ContextExecutor, id int) (bool, error) {
	return sale.OrderConfirmationItemExists(ctx, exec, id)
}

func (r *SaleRepository) GetOrderConfirmationItemRowsCount(ctx context.Context, exec boil.ContextExecutor) (int, error) {
	count, err := sale.OrderConfirmationItems().Count(ctx, exec)
	return int(count), err
}

func (r *SaleRepository) GetMostRecentOrderConfirmationItem(ctx context.Context, exec boil.ContextExecutor) (*sale.OrderConfirmationItem, error) {
	return sale.OrderConfirmationItems(qm.OrderBy("created_at DESC")).One(ctx, exec)
}

func (r *SaleRepository) GetNextEntryOrderConfirmationItemID(ctx context.Context, exec boil.ContextExecutor) (int, error) {
	currID, err := r.GetMostRecentOrderConfirmationItem(ctx, exec)
	if err != nil {
		if err == sql.ErrNoRows {
			return 1, nil
		}
		return 0, err
	}
	return currID.ID + 1, nil
}

func (r *SaleRepository) GetOrderConfirmationItemTotalCount(ctx context.Context, exec boil.ContextExecutor) (int, error) {
	count, err := sale.OrderConfirmationItems().Count(ctx, exec)
	return int(count), err
}