// Code generated by MVRP Codegen Util. DO NOT EDIT.

package sale

import (
	"context"
	"database/sql"
	"mvrp/data/model/sale"
	"mvrp/domain/dto"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
)

func (r *SaleRepository) ListAllGoodsReturnNotes(ctx context.Context, exec boil.ContextExecutor) (sale.GoodsReturnNoteSlice, error) {
	return sale.GoodsReturnNotes().All(ctx, exec)
}

/*
func (r *SaleRepository) SearchGoodsReturnNotes(ctx context.Context, exec boil.ContextExecutor, dto dto.SearchGoodsReturnNoteDTO) (sale.GoodsReturnNoteSlice, error) {
	return sale.GoodsReturnNotes(
		qm.Limit(dto.ItemsPerPage),
		qm.Offset((dto.ItemsPerPage*dto.Page)-dto.ItemsPerPage),
		// qm.GroupBy("id"),
		qm.OrderBy(dto.OrderBy+" "+"ASC"),
	).All(ctx, exec)
}
*/
func (r *SaleRepository) SearchGoodsReturnNotes(ctx context.Context, exec boil.ContextExecutor, dto dto.SearchGoodsReturnNoteDTO) (sale.GoodsReturnNoteSlice, error) {
	var queryMods []qm.QueryMod

	queryMods = append(queryMods,
		qm.Limit(dto.ItemsPerPage),
		qm.Offset((dto.ItemsPerPage*dto.Page)-dto.ItemsPerPage),
		// qm.GroupBy("id"),
		qm.OrderBy(dto.OrderBy+" "+"ASC"),
	)

	return sale.GoodsReturnNotes(queryMods...).All(ctx, exec)
}

func (r *SaleRepository) GetGoodsReturnNoteByID(ctx context.Context, exec boil.ContextExecutor, id int) (*sale.GoodsReturnNote, error) {
	return sale.FindGoodsReturnNote(ctx, exec, id)
}

func (r *SaleRepository) CreateGoodsReturnNote(ctx context.Context, exec boil.ContextExecutor, m *sale.GoodsReturnNote) error {
	/*
		id, err := r.GetNextEntryGoodsReturnNoteID(ctx, exec)
		if err != nil {
			return err
		}
		m.ID = id
	*/
	return m.Insert(ctx, exec, boil.Infer())
}

func (r *SaleRepository) UpdateGoodsReturnNote(ctx context.Context, exec boil.ContextExecutor, m *sale.GoodsReturnNote) error {
	_, err := m.Update(ctx, exec, boil.Infer())
	return err
}

func (r *SaleRepository) UpsertGoodsReturnNote(ctx context.Context, exec boil.ContextExecutor, m *sale.GoodsReturnNote) error {
	return m.Upsert(ctx, exec, true, nil, boil.Infer(), boil.Infer())
}

func (r *SaleRepository) DeleteGoodsReturnNote(ctx context.Context, exec boil.ContextExecutor, m *sale.GoodsReturnNote) error {
	_, err := m.Delete(ctx, exec)
	return err
}

func (r *SaleRepository) GoodsReturnNoteExists(ctx context.Context, exec boil.ContextExecutor, id int) (bool, error) {
	return sale.GoodsReturnNoteExists(ctx, exec, id)
}

func (r *SaleRepository) GetGoodsReturnNoteRowsCount(ctx context.Context, exec boil.ContextExecutor) (int, error) {
	count, err := sale.GoodsReturnNotes().Count(ctx, exec)
	return int(count), err
}

func (r *SaleRepository) GetMostRecentGoodsReturnNote(ctx context.Context, exec boil.ContextExecutor) (*sale.GoodsReturnNote, error) {
	return sale.GoodsReturnNotes(qm.OrderBy("created_at DESC")).One(ctx, exec)
}

func (r *SaleRepository) GetNextEntryGoodsReturnNoteID(ctx context.Context, exec boil.ContextExecutor) (int, error) {
	var maxID sql.NullInt64
	err := sale.GoodsReturnNotes(qm.Select("MAX(id)")).QueryRow(exec).Scan(&maxID)
	if err != nil {
		return 0, err
	}

	// Check if maxID is valid (non-NULL), otherwise return 1
	if !maxID.Valid {
		return 1, nil
	}
	return int(maxID.Int64) + 1, nil

	/*
		currID, err := r.GetMostRecentGoodsReturnNote(ctx, exec)
		if err != nil {
			if err == sql.ErrNoRows {
				return 1, nil
			}
			return 0, err
		}
		return currID.ID + 1, nil
	*/
}

func (r *SaleRepository) GetGoodsReturnNoteTotalCount(ctx context.Context, exec boil.ContextExecutor) (int, error) {
	count, err := sale.GoodsReturnNotes().Count(ctx, exec)
	return int(count), err
}