development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=mvrp user=postgres password=postgres sslmode=disable
  dir: data/migrate
  table: migrations

production:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=mvrp user=postgres password=postgres sslmode=disable
  dir: data/migrate
  table: migrations