// Code generated by MVRP Codegen Util. DO NOT EDIT.

package sale

import (
	"context"
	"encoding/json"
	"fmt"
	"mvrp/domain/dto"
	"mvrp/domain/service/sale"
	"mvrp/errors"
	"mvrp/htresp"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
)

const GoodsReturnNoteViewKey contextKey = "GoodsReturnNoteView"

func GoodsReturnNoteViewContext(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var resp *sale.GetGoodsReturnNoteViewResponse
		if idStr := chi.URLParam(r, "id"); idStr != "" {
			id, err := strconv.Atoi(idStr)
			if err != nil {
				htresp.RespondWithError(w, http.StatusBadRequest,
					errors.WrapError(errors.ErrTypeConversion, "ID must be an integer"),
					"Failed to convert ID to integer")
				return
			}
			svc := sale.NewSaleService()
			req := svc.NewGetGoodsReturnNoteViewRequest(r.Context(), id)
			resp, err = svc.GetGoodsReturnNoteView(req)
			if err != nil {
				htresp.RespondWithError(w, http.StatusInternalServerError,
					errors.WrapError(errors.ErrTypeService, err.Error()),
					"Failed to get GoodsReturnNoteView for context: " + err.Error())
				return
			}
		} else {
			htresp.RespondWithError(w, http.StatusBadRequest,
				errors.WrapError(errors.ErrTypeBadRequest, "ID is required"),
				"Failed to get GoodsReturnNoteView")
			return
		}
		ctx := context.WithValue(r.Context(), GoodsReturnNoteViewKey, resp)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}



func ListGoodsReturnNoteView(w http.ResponseWriter, r *http.Request) {
	svc := sale.NewSaleService()
	req := svc.NewListGoodsReturnNoteViewRequest(r.Context())
	resp, err := svc.ListGoodsReturnNoteView(req)
	if err != nil {
		htresp.RespondWithError(w, http.StatusInternalServerError,
			errors.WrapError(errors.ErrTypeService, err.Error()),
			"Failed to list GoodsReturnNoteView: " + err.Error())
		return
	}
	htresp.RespondWithJSON(w, http.StatusOK, resp, "GoodsReturnNoteView listed successfully")
	
}

func GetGoodsReturnNoteView(w http.ResponseWriter, r *http.Request) {
	value, ok := r.Context().Value(GoodsReturnNoteViewKey).(*sale.GetGoodsReturnNoteViewResponse)
	if !ok {
		htresp.RespondWithError(w, http.StatusInternalServerError,
			errors.WrapError(errors.ErrTypeAssertion,
				fmt.Sprintf("Incorrect response format, should be %T", r.Context().Value(GoodsReturnNoteViewKey))),
			"Failed to get GoodsReturnNoteView")
		return
	}
	htresp.RespondWithJSON(w, http.StatusOK, value, "GoodsReturnNoteView retrieved successfully")

	
}

func SearchGoodsReturnNoteView(w http.ResponseWriter, r *http.Request) {
	
	var dto *dto.SearchGoodsReturnNoteDTO
	err := json.NewDecoder(r.Body).Decode(&dto)
	if err != nil {
		htresp.RespondWithError(w, http.StatusBadRequest, err, "Failed to decode request body: " + err.Error())
		return
	}
	svc := sale.NewSaleService()
	req := svc.NewSearchGoodsReturnNoteViewRequest(r.Context(), *dto)
	resp, err := svc.SearchGoodsReturnNoteView(req)
	if err != nil {
		htresp.RespondWithError(w, http.StatusInternalServerError,
			errors.WrapError(errors.ErrTypeService, err.Error()),
			"Failed to search GoodsReturnNoteView: " + err.Error())
		return
	}
	htresp.RespondWithJSON(w, http.StatusOK, resp, "GoodsReturnNoteView search successful")

	
}

