// Code generated by MVRP Codegen Util. DO NOT EDIT.

package sale

import (
	"context"
	"encoding/json"
	"fmt"
	"mvrp/domain/dto"
	"mvrp/domain/service/sale"
	"mvrp/errors"
	"mvrp/htresp"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
)

const OrderConfirmationViewKey contextKey = "OrderConfirmationView"

func OrderConfirmationViewContext(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var resp *sale.GetOrderConfirmationViewResponse
		if idStr := chi.URLParam(r, "id"); idStr != "" {
			id, err := strconv.Atoi(idStr)
			if err != nil {
				htresp.RespondWithError(w, http.StatusBadRequest,
					errors.WrapError(errors.ErrTypeConversion, "ID must be an integer"),
					"Failed to convert ID to integer")
				return
			}
			svc := sale.NewSaleService()
			req := svc.NewGetOrderConfirmationViewRequest(r.Context(), id)
			resp, err = svc.GetOrderConfirmationView(req)
			if err != nil {
				htresp.RespondWithError(w, http.StatusInternalServerError,
					errors.WrapError(errors.ErrTypeService, err.Error()),
					"Failed to get OrderConfirmationView for context: " + err.Error())
				return
			}
		} else {
			htresp.RespondWithError(w, http.StatusBadRequest,
				errors.WrapError(errors.ErrTypeBadRequest, "ID is required"),
				"Failed to get OrderConfirmationView")
			return
		}
		ctx := context.WithValue(r.Context(), OrderConfirmationViewKey, resp)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}



func ListOrderConfirmationView(w http.ResponseWriter, r *http.Request) {
	svc := sale.NewSaleService()
	req := svc.NewListOrderConfirmationViewRequest(r.Context())
	resp, err := svc.ListOrderConfirmationView(req)
	if err != nil {
		htresp.RespondWithError(w, http.StatusInternalServerError,
			errors.WrapError(errors.ErrTypeService, err.Error()),
			"Failed to list OrderConfirmationView: " + err.Error())
		return
	}
	htresp.RespondWithJSON(w, http.StatusOK, resp, "OrderConfirmationView listed successfully")
	
}

func GetOrderConfirmationView(w http.ResponseWriter, r *http.Request) {
	value, ok := r.Context().Value(OrderConfirmationViewKey).(*sale.GetOrderConfirmationViewResponse)
	if !ok {
		htresp.RespondWithError(w, http.StatusInternalServerError,
			errors.WrapError(errors.ErrTypeAssertion,
				fmt.Sprintf("Incorrect response format, should be %T", r.Context().Value(OrderConfirmationViewKey))),
			"Failed to get OrderConfirmationView")
		return
	}
	htresp.RespondWithJSON(w, http.StatusOK, value, "OrderConfirmationView retrieved successfully")

	
}

func SearchOrderConfirmationView(w http.ResponseWriter, r *http.Request) {
	
	var dto *dto.SearchOrderConfirmationDTO
	err := json.NewDecoder(r.Body).Decode(&dto)
	if err != nil {
		htresp.RespondWithError(w, http.StatusBadRequest, err, "Failed to decode request body: " + err.Error())
		return
	}
	svc := sale.NewSaleService()
	req := svc.NewSearchOrderConfirmationViewRequest(r.Context(), *dto)
	resp, err := svc.SearchOrderConfirmationView(req)
	if err != nil {
		htresp.RespondWithError(w, http.StatusInternalServerError,
			errors.WrapError(errors.ErrTypeService, err.Error()),
			"Failed to search OrderConfirmationView: " + err.Error())
		return
	}
	htresp.RespondWithJSON(w, http.StatusOK, resp, "OrderConfirmationView search successful")

	
}

