// Code generated by MVRP Codegen Util. DO NOT EDIT.

package dto

import (
    "mvrp/data/model/base"
    "mvrp/data/model/purchase"
)

type SearchPurchaseOrderDTO struct {
    Keyword      string                             `json:"keyword"`
    ItemsPerPage int                                `json:"items_per_page"`
    Page         int                                `json:"page"`
    SortBy       string                             `json:"sort_by"`
    OrderBy      string                             `json:"order_by"`
}

type CreatePurchaseOrderDTO struct {
    base.BaseDocument                 `json:"base_document"`
    purchase.PurchaseOrder                 `json:"purchase_order"`
    Items []CreatePurchaseOrderItemDTO                     `json:"items"`
}

type UpdatePurchaseOrderDTO struct {
    base.BaseDocument                 `json:"base_document"`
    purchase.PurchaseOrder                 `json:"purchase_order"`
    Items []UpdatePurchaseOrderItemDTO                     `json:"items"`
}

type SearchPurchaseOrderItemDTO struct {
    Keyword      string                             `json:"keyword"`
    ItemsPerPage int                                `json:"items_per_page"`
    Page         int                                `json:"page"`
    SortBy       string                             `json:"sort_by"`
    OrderBy      string                             `json:"order_by"`
}

type CreatePurchaseOrderItemDTO struct {
    base.BaseDocumentItem                 `json:"base_document_item"`
    purchase.PurchaseOrderItem                 `json:"purchase_order_item"`
}

type UpdatePurchaseOrderItemDTO struct {
    base.BaseDocumentItem                 `json:"base_document_item"`
    purchase.PurchaseOrderItem                 `json:"purchase_order_item"`
}

type SearchGoodsReceiptNoteDTO struct {
    Keyword      string                             `json:"keyword"`
    ItemsPerPage int                                `json:"items_per_page"`
    Page         int                                `json:"page"`
    SortBy       string                             `json:"sort_by"`
    OrderBy      string                             `json:"order_by"`
}

type CreateGoodsReceiptNoteDTO struct {
    base.BaseDocument                 `json:"base_document"`
    purchase.GoodsReceiptNote                 `json:"goods_receipt_note"`
    Items []CreateGoodsReceiptNoteItemDTO                     `json:"items"`
}

type UpdateGoodsReceiptNoteDTO struct {
    base.BaseDocument                 `json:"base_document"`
    purchase.GoodsReceiptNote                 `json:"goods_receipt_note"`
    Items []UpdateGoodsReceiptNoteItemDTO                     `json:"items"`
}

type SearchGoodsReceiptNoteItemDTO struct {
    Keyword      string                             `json:"keyword"`
    ItemsPerPage int                                `json:"items_per_page"`
    Page         int                                `json:"page"`
    SortBy       string                             `json:"sort_by"`
    OrderBy      string                             `json:"order_by"`
}

type CreateGoodsReceiptNoteItemDTO struct {
    base.BaseDocumentItem                 `json:"base_document_item"`
    purchase.GoodsReceiptNoteItem                 `json:"goods_receipt_note_item"`
}

type UpdateGoodsReceiptNoteItemDTO struct {
    base.BaseDocumentItem                 `json:"base_document_item"`
    purchase.GoodsReceiptNoteItem                 `json:"goods_receipt_note_item"`
}

type SearchRequestForQuotationDTO struct {
    Keyword      string                             `json:"keyword"`
    ItemsPerPage int                                `json:"items_per_page"`
    Page         int                                `json:"page"`
    SortBy       string                             `json:"sort_by"`
    OrderBy      string                             `json:"order_by"`
}

type CreateRequestForQuotationDTO struct {
    base.BaseDocument                 `json:"base_document"`
    purchase.RequestForQuotation                 `json:"request_for_quotation"`
    Items []CreateRequestForQuotationItemDTO                     `json:"items"`
}

type UpdateRequestForQuotationDTO struct {
    base.BaseDocument                 `json:"base_document"`
    purchase.RequestForQuotation                 `json:"request_for_quotation"`
    Items []UpdateRequestForQuotationItemDTO                     `json:"items"`
}

type SearchRequestForQuotationItemDTO struct {
    Keyword      string                             `json:"keyword"`
    ItemsPerPage int                                `json:"items_per_page"`
    Page         int                                `json:"page"`
    SortBy       string                             `json:"sort_by"`
    OrderBy      string                             `json:"order_by"`
}

type CreateRequestForQuotationItemDTO struct {
    base.BaseDocumentItem                 `json:"base_document_item"`
    purchase.RequestForQuotationItem                 `json:"request_for_quotation_item"`
}

type UpdateRequestForQuotationItemDTO struct {
    base.BaseDocumentItem                 `json:"base_document_item"`
    purchase.RequestForQuotationItem                 `json:"request_for_quotation_item"`
}