// Code generated by MVRP Codegen Util. DO NOT EDIT.

package inventory

import (
	"context"
	"database/sql"
	"mvrp/data/model/inventory"
	"mvrp/domain/dto"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
)

func (r *InventoryRepository) ListAllGoodsIssueNotes(ctx context.Context, exec boil.ContextExecutor) (inventory.GoodsIssueNoteSlice, error) {
	return inventory.GoodsIssueNotes().All(ctx, exec)
}
func (r *InventoryRepository) SearchGoodsIssueNotes(ctx context.Context, exec boil.ContextExecutor, dto dto.SearchGoodsIssueNoteDTO) (inventory.GoodsIssueNoteSlice, error) {
	return inventory.GoodsIssueNotes(
		qm.Limit(dto.ItemsPerPage),
		qm.Offset((dto.ItemsPerPage*dto.Page)-dto.ItemsPerPage),
		// qm.GroupBy("id"),
		qm.OrderBy(dto.OrderBy+" "+"ASC"),
	).All(ctx, exec)
}

func (r *InventoryRepository) GetGoodsIssueNoteByID(ctx context.Context, exec boil.ContextExecutor, id int) (*inventory.GoodsIssueNote, error) {
	return inventory.FindGoodsIssueNote(ctx, exec, id)
}

func (r *InventoryRepository) CreateGoodsIssueNote(ctx context.Context, exec boil.ContextExecutor, m *inventory.GoodsIssueNote) error {
	id, err := r.GetNextEntryGoodsIssueNoteID(ctx, exec)
	if err != nil {
		return err
	}
	m.ID = id
	return m.Insert(ctx, exec, boil.Infer())
}

func (r *InventoryRepository) UpdateGoodsIssueNote(ctx context.Context, exec boil.ContextExecutor, m *inventory.GoodsIssueNote) error {
	_, err := m.Update(ctx, exec, boil.Infer())
	return err
}

func (r *InventoryRepository) UpsertGoodsIssueNote(ctx context.Context, exec boil.ContextExecutor, m *inventory.GoodsIssueNote) error {
	return m.Upsert(ctx, exec, true, nil, boil.Infer(), boil.Infer())
}

func (r *InventoryRepository) DeleteGoodsIssueNote(ctx context.Context, exec boil.ContextExecutor, m *inventory.GoodsIssueNote) error {
	_, err := m.Delete(ctx, exec)
	return err
}

func (r *InventoryRepository) GoodsIssueNoteExists(ctx context.Context, exec boil.ContextExecutor, id int) (bool, error) {
	return inventory.GoodsIssueNoteExists(ctx, exec, id)
}

func (r *InventoryRepository) GetGoodsIssueNoteRowsCount(ctx context.Context, exec boil.ContextExecutor) (int, error) {
	count, err := inventory.GoodsIssueNotes().Count(ctx, exec)
	return int(count), err
}

func (r *InventoryRepository) GetMostRecentGoodsIssueNote(ctx context.Context, exec boil.ContextExecutor) (*inventory.GoodsIssueNote, error) {
	return inventory.GoodsIssueNotes(qm.OrderBy("created_at DESC")).One(ctx, exec)
}

func (r *InventoryRepository) GetNextEntryGoodsIssueNoteID(ctx context.Context, exec boil.ContextExecutor) (int, error) {
	currID, err := r.GetMostRecentGoodsIssueNote(ctx, exec)
	if err != nil {
		if err == sql.ErrNoRows {
			return 1, nil
		}
		return 0, err
	}
	return currID.ID + 1, nil
}

func (r *InventoryRepository) GetGoodsIssueNoteTotalCount(ctx context.Context, exec boil.ContextExecutor) (int, error) {
	count, err := inventory.GoodsIssueNotes().Count(ctx, exec)
	return int(count), err
}