// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sale

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// SalesOrderView is an object representing the database table.
type SalesOrderView struct {
	ID                             null.Int             `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	BaseDocumentID                 null.Int             `boil:"base_document_id" json:"base_document_id,omitempty" toml:"base_document_id" yaml:"base_document_id,omitempty"`
	SalesOrderNumber               null.String          `boil:"sales_order_number" json:"sales_order_number,omitempty" toml:"sales_order_number" yaml:"sales_order_number,omitempty"`
	VendorID                       null.Int             `boil:"vendor_id" json:"vendor_id,omitempty" toml:"vendor_id" yaml:"vendor_id,omitempty"`
	CustomerID                     null.Int             `boil:"customer_id" json:"customer_id,omitempty" toml:"customer_id" yaml:"customer_id,omitempty"`
	SalesRepresentativeInformation null.String          `boil:"sales_representative_information" json:"sales_representative_information,omitempty" toml:"sales_representative_information" yaml:"sales_representative_information,omitempty"`
	ShipToInformation              null.String          `boil:"ship_to_information" json:"ship_to_information,omitempty" toml:"ship_to_information" yaml:"ship_to_information,omitempty"`
	ShipFromInformation            null.String          `boil:"ship_from_information" json:"ship_from_information,omitempty" toml:"ship_from_information" yaml:"ship_from_information,omitempty"`
	PaymentDueDate                 null.Time            `boil:"payment_due_date" json:"payment_due_date,omitempty" toml:"payment_due_date" yaml:"payment_due_date,omitempty"`
	OrderStatus                    NullSalesOrderStatus `boil:"order_status" json:"order_status,omitempty" toml:"order_status" yaml:"order_status,omitempty"`
	BaseDocument                   null.JSON            `boil:"base_document" json:"base_document,omitempty" toml:"base_document" yaml:"base_document,omitempty"`
	SalesOrderItems                null.JSON            `boil:"sales_order_items" json:"sales_order_items,omitempty" toml:"sales_order_items" yaml:"sales_order_items,omitempty"`
}

var SalesOrderViewColumns = struct {
	ID                             string
	BaseDocumentID                 string
	SalesOrderNumber               string
	VendorID                       string
	CustomerID                     string
	SalesRepresentativeInformation string
	ShipToInformation              string
	ShipFromInformation            string
	PaymentDueDate                 string
	OrderStatus                    string
	BaseDocument                   string
	SalesOrderItems                string
}{
	ID:                             "id",
	BaseDocumentID:                 "base_document_id",
	SalesOrderNumber:               "sales_order_number",
	VendorID:                       "vendor_id",
	CustomerID:                     "customer_id",
	SalesRepresentativeInformation: "sales_representative_information",
	ShipToInformation:              "ship_to_information",
	ShipFromInformation:            "ship_from_information",
	PaymentDueDate:                 "payment_due_date",
	OrderStatus:                    "order_status",
	BaseDocument:                   "base_document",
	SalesOrderItems:                "sales_order_items",
}

var SalesOrderViewTableColumns = struct {
	ID                             string
	BaseDocumentID                 string
	SalesOrderNumber               string
	VendorID                       string
	CustomerID                     string
	SalesRepresentativeInformation string
	ShipToInformation              string
	ShipFromInformation            string
	PaymentDueDate                 string
	OrderStatus                    string
	BaseDocument                   string
	SalesOrderItems                string
}{
	ID:                             "sales_order_view.id",
	BaseDocumentID:                 "sales_order_view.base_document_id",
	SalesOrderNumber:               "sales_order_view.sales_order_number",
	VendorID:                       "sales_order_view.vendor_id",
	CustomerID:                     "sales_order_view.customer_id",
	SalesRepresentativeInformation: "sales_order_view.sales_representative_information",
	ShipToInformation:              "sales_order_view.ship_to_information",
	ShipFromInformation:            "sales_order_view.ship_from_information",
	PaymentDueDate:                 "sales_order_view.payment_due_date",
	OrderStatus:                    "sales_order_view.order_status",
	BaseDocument:                   "sales_order_view.base_document",
	SalesOrderItems:                "sales_order_view.sales_order_items",
}

// Generated where

type whereHelperNullSalesOrderStatus struct{ field string }

func (w whereHelperNullSalesOrderStatus) EQ(x NullSalesOrderStatus) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelperNullSalesOrderStatus) NEQ(x NullSalesOrderStatus) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelperNullSalesOrderStatus) LT(x NullSalesOrderStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperNullSalesOrderStatus) LTE(x NullSalesOrderStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperNullSalesOrderStatus) GT(x NullSalesOrderStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperNullSalesOrderStatus) GTE(x NullSalesOrderStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperNullSalesOrderStatus) IN(slice []NullSalesOrderStatus) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperNullSalesOrderStatus) NIN(slice []NullSalesOrderStatus) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelperNullSalesOrderStatus) IsNull() qm.QueryMod { return qmhelper.WhereIsNull(w.field) }
func (w whereHelperNullSalesOrderStatus) IsNotNull() qm.QueryMod {
	return qmhelper.WhereIsNotNull(w.field)
}

var SalesOrderViewWhere = struct {
	ID                             whereHelpernull_Int
	BaseDocumentID                 whereHelpernull_Int
	SalesOrderNumber               whereHelpernull_String
	VendorID                       whereHelpernull_Int
	CustomerID                     whereHelpernull_Int
	SalesRepresentativeInformation whereHelpernull_String
	ShipToInformation              whereHelpernull_String
	ShipFromInformation            whereHelpernull_String
	PaymentDueDate                 whereHelpernull_Time
	OrderStatus                    whereHelperNullSalesOrderStatus
	BaseDocument                   whereHelpernull_JSON
	SalesOrderItems                whereHelpernull_JSON
}{
	ID:                             whereHelpernull_Int{field: "\"sale\".\"sales_order_view\".\"id\""},
	BaseDocumentID:                 whereHelpernull_Int{field: "\"sale\".\"sales_order_view\".\"base_document_id\""},
	SalesOrderNumber:               whereHelpernull_String{field: "\"sale\".\"sales_order_view\".\"sales_order_number\""},
	VendorID:                       whereHelpernull_Int{field: "\"sale\".\"sales_order_view\".\"vendor_id\""},
	CustomerID:                     whereHelpernull_Int{field: "\"sale\".\"sales_order_view\".\"customer_id\""},
	SalesRepresentativeInformation: whereHelpernull_String{field: "\"sale\".\"sales_order_view\".\"sales_representative_information\""},
	ShipToInformation:              whereHelpernull_String{field: "\"sale\".\"sales_order_view\".\"ship_to_information\""},
	ShipFromInformation:            whereHelpernull_String{field: "\"sale\".\"sales_order_view\".\"ship_from_information\""},
	PaymentDueDate:                 whereHelpernull_Time{field: "\"sale\".\"sales_order_view\".\"payment_due_date\""},
	OrderStatus:                    whereHelperNullSalesOrderStatus{field: "\"sale\".\"sales_order_view\".\"order_status\""},
	BaseDocument:                   whereHelpernull_JSON{field: "\"sale\".\"sales_order_view\".\"base_document\""},
	SalesOrderItems:                whereHelpernull_JSON{field: "\"sale\".\"sales_order_view\".\"sales_order_items\""},
}

var (
	salesOrderViewAllColumns            = []string{"id", "base_document_id", "sales_order_number", "vendor_id", "customer_id", "sales_representative_information", "ship_to_information", "ship_from_information", "payment_due_date", "order_status", "base_document", "sales_order_items"}
	salesOrderViewColumnsWithoutDefault = []string{}
	salesOrderViewColumnsWithDefault    = []string{"id", "base_document_id", "sales_order_number", "vendor_id", "customer_id", "sales_representative_information", "ship_to_information", "ship_from_information", "payment_due_date", "order_status", "base_document", "sales_order_items"}
	salesOrderViewPrimaryKeyColumns     = []string{}
	salesOrderViewGeneratedColumns      = []string{}
)

type (
	// SalesOrderViewSlice is an alias for a slice of pointers to SalesOrderView.
	// This should almost always be used instead of []SalesOrderView.
	SalesOrderViewSlice []*SalesOrderView
	// SalesOrderViewHook is the signature for custom SalesOrderView hook methods
	SalesOrderViewHook func(context.Context, boil.ContextExecutor, *SalesOrderView) error

	salesOrderViewQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	salesOrderViewType           = reflect.TypeOf(&SalesOrderView{})
	salesOrderViewMapping        = queries.MakeStructMapping(salesOrderViewType)
	salesOrderViewInsertCacheMut sync.RWMutex
	salesOrderViewInsertCache    = make(map[string]insertCache)
	salesOrderViewUpdateCacheMut sync.RWMutex
	salesOrderViewUpdateCache    = make(map[string]updateCache)
	salesOrderViewUpsertCacheMut sync.RWMutex
	salesOrderViewUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
	// These are used in some views
	_ = fmt.Sprintln("")
	_ = reflect.Int
	_ = strings.Builder{}
	_ = sync.Mutex{}
	_ = strmangle.Plural("")
	_ = strconv.IntSize
)

var salesOrderViewAfterSelectMu sync.Mutex
var salesOrderViewAfterSelectHooks []SalesOrderViewHook

var salesOrderViewBeforeInsertMu sync.Mutex
var salesOrderViewBeforeInsertHooks []SalesOrderViewHook
var salesOrderViewAfterInsertMu sync.Mutex
var salesOrderViewAfterInsertHooks []SalesOrderViewHook

var salesOrderViewBeforeUpsertMu sync.Mutex
var salesOrderViewBeforeUpsertHooks []SalesOrderViewHook
var salesOrderViewAfterUpsertMu sync.Mutex
var salesOrderViewAfterUpsertHooks []SalesOrderViewHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SalesOrderView) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range salesOrderViewAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SalesOrderView) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range salesOrderViewBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SalesOrderView) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range salesOrderViewAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SalesOrderView) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range salesOrderViewBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SalesOrderView) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range salesOrderViewAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSalesOrderViewHook registers your hook function for all future operations.
func AddSalesOrderViewHook(hookPoint boil.HookPoint, salesOrderViewHook SalesOrderViewHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		salesOrderViewAfterSelectMu.Lock()
		salesOrderViewAfterSelectHooks = append(salesOrderViewAfterSelectHooks, salesOrderViewHook)
		salesOrderViewAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		salesOrderViewBeforeInsertMu.Lock()
		salesOrderViewBeforeInsertHooks = append(salesOrderViewBeforeInsertHooks, salesOrderViewHook)
		salesOrderViewBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		salesOrderViewAfterInsertMu.Lock()
		salesOrderViewAfterInsertHooks = append(salesOrderViewAfterInsertHooks, salesOrderViewHook)
		salesOrderViewAfterInsertMu.Unlock()
	case boil.BeforeUpsertHook:
		salesOrderViewBeforeUpsertMu.Lock()
		salesOrderViewBeforeUpsertHooks = append(salesOrderViewBeforeUpsertHooks, salesOrderViewHook)
		salesOrderViewBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		salesOrderViewAfterUpsertMu.Lock()
		salesOrderViewAfterUpsertHooks = append(salesOrderViewAfterUpsertHooks, salesOrderViewHook)
		salesOrderViewAfterUpsertMu.Unlock()
	}
}

// One returns a single salesOrderView record from the query.
func (q salesOrderViewQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SalesOrderView, error) {
	o := &SalesOrderView{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sale: failed to execute a one query for sales_order_view")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SalesOrderView records from the query.
func (q salesOrderViewQuery) All(ctx context.Context, exec boil.ContextExecutor) (SalesOrderViewSlice, error) {
	var o []*SalesOrderView

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sale: failed to assign all query results to SalesOrderView slice")
	}

	if len(salesOrderViewAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SalesOrderView records in the query.
func (q salesOrderViewQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sale: failed to count sales_order_view rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q salesOrderViewQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sale: failed to check if sales_order_view exists")
	}

	return count > 0, nil
}

// SalesOrderViews retrieves all the records using an executor.
func SalesOrderViews(mods ...qm.QueryMod) salesOrderViewQuery {
	mods = append(mods, qm.From("\"sale\".\"sales_order_view\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"sale\".\"sales_order_view\".*"})
	}

	return salesOrderViewQuery{q}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SalesOrderView) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sale: no sales_order_view provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(salesOrderViewColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	salesOrderViewInsertCacheMut.RLock()
	cache, cached := salesOrderViewInsertCache[key]
	salesOrderViewInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			salesOrderViewAllColumns,
			salesOrderViewColumnsWithDefault,
			salesOrderViewColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(salesOrderViewType, salesOrderViewMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(salesOrderViewType, salesOrderViewMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"sale\".\"sales_order_view\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"sale\".\"sales_order_view\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sale: unable to insert into sales_order_view")
	}

	if !cached {
		salesOrderViewInsertCacheMut.Lock()
		salesOrderViewInsertCache[key] = cache
		salesOrderViewInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SalesOrderView) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sale: no sales_order_view provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(salesOrderViewColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	salesOrderViewUpsertCacheMut.RLock()
	cache, cached := salesOrderViewUpsertCache[key]
	salesOrderViewUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			salesOrderViewAllColumns,
			salesOrderViewColumnsWithDefault,
			salesOrderViewColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			salesOrderViewAllColumns,
			salesOrderViewPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sale: unable to upsert sales_order_view, could not build update column list")
		}

		ret := strmangle.SetComplement(salesOrderViewAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(salesOrderViewPrimaryKeyColumns) == 0 {
				return errors.New("sale: unable to upsert sales_order_view, could not build conflict column list")
			}

			conflict = make([]string, len(salesOrderViewPrimaryKeyColumns))
			copy(conflict, salesOrderViewPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"sale\".\"sales_order_view\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(salesOrderViewType, salesOrderViewMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(salesOrderViewType, salesOrderViewMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sale: unable to upsert sales_order_view")
	}

	if !cached {
		salesOrderViewUpsertCacheMut.Lock()
		salesOrderViewUpsertCache[key] = cache
		salesOrderViewUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
